"""step9_api_contract_rename

Revision ID: 2ba03d5c9aa4
Revises: bc5089a2ab26
Create Date: 2026-09-30 22:31:32.691695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba03d5c9aa4'
down_revision: Union[str, None] = 'bc5089a2ab26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('bidang', sa.String(length=150), nullable=True, comment='Sektor atau bidang regulasi (misal: Perbankan, Pasar Modal, IKNB, BMKS)'))
    op.add_column('documents', sa.Column('naming_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Format urutan komponen penamaan berkas pilihan pengguna'))
    op.add_column('documents', sa.Column('naming_separator', sa.String(length=1), nullable=True, comment='Pemisah komponen penamaan berkas'))
    op.add_column('scan_sessions', sa.Column('naming_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Format penamaan berkas yang dipilih saat pull'))
    op.add_column('scan_sessions', sa.Column('naming_separator', sa.String(length=1), nullable=True, comment='Pemisah komponen penamaan berkas'))
    op.add_column('scraping_sources', sa.Column('default_naming_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Format penamaan berkas default untuk sumber ini'))
    op.add_column('scraping_sources', sa.Column('default_naming_separator', sa.String(length=1), nullable=True, comment='Pemisah komponen penamaan berkas default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sources', 'default_naming_separator')
    op.drop_column('scraping_sources', 'default_naming_format')
    op.drop_column('scan_sessions', 'naming_separator')
    op.drop_column('scan_sessions', 'naming_format')
    op.drop_column('documents', 'naming_separator')
    op.drop_column('documents', 'naming_format')
    op.drop_column('documents', 'bidang')
    # ### end Alembic commands ###
