"""step10_robust_scan

Revision ID: 02779701b550
Revises: 2ba03d5c9aa4
Create Date: 2026-10-01 18:29:25.695548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02779701b550'
down_revision: Union[str, None] = '2ba03d5c9aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_candidates', sa.Column('document_title', sa.String(length=500), nullable=True, comment='Nama dokumen / judul regulasi yang tertera di situs'))
    op.add_column('scan_candidates', sa.Column('detail_url', sa.Text(), nullable=True, comment='Halaman detail tempat lampiran ditemukan'))
    op.add_column('scan_candidates', sa.Column('final_url', sa.Text(), nullable=True, comment='URL akhir setelah mengikuti redirect'))
    op.add_column('scan_candidates', sa.Column('doc_kind', sa.String(length=30), nullable=True, comment='Jenis/peran dokumen: utama | abstrak | faq | lampiran | lainnya'))
    op.add_column('scan_candidates', sa.Column('regulation_number', sa.String(length=255), nullable=True, comment='Nomor regulasi yang terbaca tanpa membuka PDF'))
    op.add_column('scan_candidates', sa.Column('regulation_type', sa.String(length=100), nullable=True, comment='Jenis regulasi ternormalisasi'))
    op.add_column('scan_candidates', sa.Column('bidang', sa.String(length=100), nullable=True, comment='Sektor/bidang regulasi yang terbaca dari situs'))
    op.add_column('scan_candidates', sa.Column('sub_bidang', sa.String(length=100), nullable=True, comment='Sub-sektor regulasi yang terbaca dari situs'))
    op.add_column('scan_candidates', sa.Column('release_date', sa.Date(), nullable=True, comment='Tanggal rilis/penetapan regulasi yang terbaca dari situs'))
    op.add_column('scan_candidates', sa.Column('size_source', sa.String(length=10), nullable=True, comment='Sumber penentuan ukuran berkas: listing | head | range | unknown'))
    op.add_column('scan_candidates', sa.Column('source_path', sa.Text(), nullable=True, comment='Jalur folder relatif sumber, misal untuk OneDrive'))
    op.add_column('scan_sessions', sa.Column('blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True jika pemindaian terhenti akibat captcha/Cloudflare/WAF'))
    op.add_column('scan_sessions', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Statistik detail hasil pemindaian (regulations_found, pdfs_found, per doc_kind, pages_visited, requests_made, duration_seconds)'))
    op.add_column('scan_sessions', sa.Column('crawler_adapter', sa.String(length=50), nullable=True, comment='Adapter crawler yang mengeksekusi (sharepoint_postback, jdih_api, onedrive_share, generic_html)'))
    op.add_column('scraping_sources', sa.Column('crawler_adapter', sa.String(length=50), nullable=True, comment='Adapter crawler khusus: sharepoint_postback | jdih_api | onedrive_share | generic_html'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_sources', 'crawler_adapter')
    op.drop_column('scan_sessions', 'crawler_adapter')
    op.drop_column('scan_sessions', 'stats')
    op.drop_column('scan_sessions', 'blocked')
    op.drop_column('scan_candidates', 'source_path')
    op.drop_column('scan_candidates', 'size_source')
    op.drop_column('scan_candidates', 'release_date')
    op.drop_column('scan_candidates', 'sub_bidang')
    op.drop_column('scan_candidates', 'bidang')
    op.drop_column('scan_candidates', 'regulation_type')
    op.drop_column('scan_candidates', 'regulation_number')
    op.drop_column('scan_candidates', 'doc_kind')
    op.drop_column('scan_candidates', 'final_url')
    op.drop_column('scan_candidates', 'detail_url')
    op.drop_column('scan_candidates', 'document_title')
    # ### end Alembic commands ###
