"""step10b_match_warning_and_effective_date

Revision ID: 17e384880e5d
Revises: 02779701b550
Create Date: 2026-10-01 21:50:58.375146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e384880e5d'
down_revision: Union[str, None] = '02779701b550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_candidates', sa.Column('effective_date', sa.Date(), nullable=True, comment='Tanggal mulai berlaku regulasi yang terbaca dari situs'))
    op.add_column('scan_candidates', sa.Column('match_warning', sa.Text(), nullable=True, comment='Peringatan ketidakcocokan metadata regulasi dengan nama berkas'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_candidates', 'match_warning')
    op.drop_column('scan_candidates', 'effective_date')
    # ### end Alembic commands ###
