"""fase1 baseline schema

Revision ID: 19ab55fb7e4e
Revises: f841df680a0f
Create Date: 2026-09-26 15:20:47.918228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '19ab55fb7e4e'
down_revision: Union[str, None] = 'f841df680a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Aktifkan ekstensi pgvector sebelum tipe Vector digunakan
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama kategori'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='FK ke kategori induk untuk struktur hierarkis folder KB'),
    sa.Column('auto_created', sa.Boolean(), nullable=False, comment='Apakah kategori ini dibuat secara otomatis oleh sistem klasifikasi'),
    sa.Column('classification_rule', sa.Text(), nullable=True, comment='Aturan / regex / prompt klasifikasi otomatis'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('job_ingest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('scraping', 'unggah_manual', 'sinkron_folder', name='jenisjobingest', native_enum=False), nullable=False, comment='Jenis job: scraping | unggah_manual | sinkron_folder'),
    sa.Column('source_ref', sa.String(length=255), nullable=True, comment='Referensi sumber, misal nama file, link, atau folder'),
    sa.Column('triggered_by', sa.String(length=100), nullable=True, comment='Pemicu job, misal user email / system / scraper id'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu job dimulai'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu job selesai dieksekusi'),
    sa.Column('status', sa.Enum('antrian', 'berjalan', 'selesai', 'gagal', name='statusjobingest', native_enum=False), nullable=False, comment='Status eksekusi: antrian | berjalan | selesai | gagal'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='Jumlah dokumen berhasil diproses'),
    sa.Column('duplicate_count', sa.Integer(), nullable=False, comment='Jumlah dokumen duplikat yang diabaikan'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='Jumlah dokumen yang gagal diproses'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_ingest_id'), 'job_ingest', ['id'], unique=False)
    op.create_table('scraping_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama/label situs sumber scraping, misal: JDIH OJK'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='URL situs sumber scraping (wajib unik)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Status aktif/non-aktif situs sumber (default: True)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu pencatatan situs sumber'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu terakhir situs sumber diubah'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_sources_id'), 'scraping_sources', ['id'], unique=False)
    op.create_index(op.f('ix_scraping_sources_url'), 'scraping_sources', ['url'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Judul lengkap dokumen regulasi'),
    sa.Column('regulation_number', sa.String(length=100), nullable=True, comment='Nomor regulasi, misal: PP-24-2005'),
    sa.Column('regulation_type', sa.String(length=100), nullable=True, comment='Jenis regulasi (misal: UU, PP, Permen, Perda)'),
    sa.Column('release_date', sa.Date(), nullable=True, comment='Tanggal terbit regulasi'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='URL sumber dokumen di web'),
    sa.Column('file_path_pdf', sa.Text(), nullable=False, comment='Path relatif file PDF asli terhadap STORAGE_PATH, misal: pdf/3fa1c2d4e5f6_nama.pdf'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash file untuk deduplikasi (sesuai ADR-05 / KEP-06)'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='Ukuran file PDF dalam bytes (pasangan pembanding wajib bersama file_hash)'),
    sa.Column('standardized_filename', sa.String(length=255), nullable=True, comment='Nama file yang sudah distandarisasi'),
    sa.Column('access_classification', sa.Enum('publik', 'non_publik', name='klasifikasiakses', native_enum=False), nullable=False, comment='Klasifikasi akses: publik | non_publik (wajib kepatuhan NDA sebelum kirim ke AI eksternal)'),
    sa.Column('document_role', sa.Enum('corpus_eksisting', 'draft_kajian', name='perandokumen', native_enum=False), nullable=False, comment='Peran dokumen: corpus_eksisting | draft_kajian (FR-SCR-04a: wajib dinyatakan)'),
    sa.Column('status_keberlakuan', sa.Enum('berlaku', 'diubah', 'dicabut', 'tidak_diketahui', name='statuskeberlakuan', native_enum=False), nullable=False, comment='Status keberlakuan: berlaku | diubah | dicabut | tidak_diketahui'),
    sa.Column('processing_status', sa.Enum('diterima', 'diproses', 'perlu_koreksi', 'terindeks', 'gagal', 'ditolak', name='statuspemrosesan', native_enum=False), nullable=False, comment='Status pemrosesan pipeline: diterima | diproses | perlu_koreksi | terindeks | gagal | ditolak'),
    sa.Column('extraction_method', sa.Enum('teks_langsung', 'ocr', name='metodeekstraksi', native_enum=False), nullable=True, comment='Metode ekstraksi teks: teks_langsung | ocr'),
    sa.Column('full_text', sa.Text(), nullable=True, comment='Teks mentah hasil ekstraksi dokumen lengkap'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='FK ke kategori / folder KB'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='FK ke job ingest terkait'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_ingest.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'file_size_bytes', name='uq_documents_hash_size')
    )
    op.create_index(op.f('ix_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.create_index(op.f('ix_documents_document_role'), 'documents', ['document_role'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_regulation_number'), 'documents', ['regulation_number'], unique=False)
    op.create_index(op.f('ix_documents_status_keberlakuan'), 'documents', ['status_keberlakuan'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='FK ke diri sendiri: mendukung struktur rekursif Bab → Pasal → Ayat → Huruf'),
    sa.Column('chapter_title', sa.String(length=255), nullable=True, comment='Judul bab, misal: BAB II'),
    sa.Column('article_number', sa.String(length=50), nullable=False, comment='Nomor pasal/ayat, misal: Pasal 5 | Ayat (1) | a.'),
    sa.Column('content_text', sa.Text(), nullable=False, comment='Isi teks mentah pasal/ayat ini'),
    sa.Column('level', sa.String(length=20), nullable=False, comment='Level hierarki: bab | pasal | ayat | huruf'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='Urutan tampil dalam dokumen (untuk sort yang benar)'),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True, comment='Embedding 1536-dim untuk semantic search (diisi pipeline ML)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_document_id'), 'articles', ['document_id'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_parent_id'), 'articles', ['parent_id'], unique=False)
    op.create_table('legal_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='Dokumen sumber yang memuat rujukan'),
    sa.Column('cited_text', sa.Text(), nullable=False, comment='Teks kutipan rujukan dasar hukum'),
    sa.Column('referenced_document_id', sa.Integer(), nullable=True, comment='FK ke dokumen yang dirujuk jika sudah ada di KB'),
    sa.Column('referenced_document_status', sa.Enum('berlaku', 'diubah', 'dicabut', 'tidak_diketahui', name='statuskeberlakuan', native_enum=False), nullable=True, comment='Status keberlakuan dokumen yang dirujuk saat rujukan dibuat'),
    sa.Column('reference_type', sa.Enum('dasar_hukum', 'rujukan_pasal', 'pencabutan', 'perubahan', name='jenisrujukan', native_enum=False), nullable=False, comment='Tipe rujukan: dasar_hukum | rujukan_pasal | pencabutan | perubahan'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_references_document_id'), 'legal_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_legal_references_id'), 'legal_references', ['id'], unique=False)
    op.create_index(op.f('ix_legal_references_referenced_document_id'), 'legal_references', ['referenced_document_id'], unique=False)
    op.create_table('article_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=False, comment='Pasal yang merujuk / mengubah'),
    sa.Column('target_article_id', sa.Integer(), nullable=True, comment='Pasal yang dirujuk / diubah (nullable jika belum ada di KB)'),
    sa.Column('target_citation_text', sa.String(length=255), nullable=True, comment='Teks sitiran target sebagai fallback saat pasal target belum ada di KB'),
    sa.Column('relation_type', sa.String(length=50), nullable=False, comment='Tipe relasi: MENGUBAH | MENCABUT | MERUJUK | MELENGKAPI'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_references_id'), 'article_references', ['id'], unique=False)
    op.create_index(op.f('ix_article_references_source_article_id'), 'article_references', ['source_article_id'], unique=False)
    op.create_index(op.f('ix_article_references_target_article_id'), 'article_references', ['target_article_id'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Kode aksi: LOGIN | UPLOAD_DOCUMENT | dsb.',
               existing_comment='Kode aksi: LOGIN | DOWNLOAD_PDF | DELETE_DOC | dsb.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               comment='Kode aksi: LOGIN | DOWNLOAD_PDF | DELETE_DOC | dsb.',
               existing_comment='Kode aksi: LOGIN | UPLOAD_DOCUMENT | dsb.',
               existing_nullable=False)
    op.drop_index(op.f('ix_article_references_target_article_id'), table_name='article_references')
    op.drop_index(op.f('ix_article_references_source_article_id'), table_name='article_references')
    op.drop_index(op.f('ix_article_references_id'), table_name='article_references')
    op.drop_table('article_references')
    op.drop_index(op.f('ix_legal_references_referenced_document_id'), table_name='legal_references')
    op.drop_index(op.f('ix_legal_references_id'), table_name='legal_references')
    op.drop_index(op.f('ix_legal_references_document_id'), table_name='legal_references')
    op.drop_table('legal_references')
    op.drop_index(op.f('ix_articles_parent_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_document_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_documents_status_keberlakuan'), table_name='documents')
    op.drop_index(op.f('ix_documents_regulation_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_role'), table_name='documents')
    op.drop_index(op.f('ix_documents_category_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_scraping_sources_url'), table_name='scraping_sources')
    op.drop_index(op.f('ix_scraping_sources_id'), table_name='scraping_sources')
    op.drop_table('scraping_sources')
    op.drop_index(op.f('ix_job_ingest_id'), table_name='job_ingest')
    op.drop_table('job_ingest')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
