"""step6_local_folder

Revision ID: 39905e7be840
Revises: 5467cc220a1b
Create Date: 2026-09-26 21:25:36.024160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39905e7be840'
down_revision: Union[str, None] = '5467cc220a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='ID sumber dokumen pemilik berkas'),
    sa.Column('relative_path', sa.Text(), nullable=False, comment='Jalur relatif berkas terhadap akar sumber (pemisah /)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='Ukuran berkas dalam bytes saat terakhir dipindai'),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=False, comment='Waktu modifikasi berkas (mtime) saat terakhir dipindai'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash dari konten berkas'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='ID dokumen regulasi yang dihasilkan (jika berhasil/duplikat)'),
    sa.Column('last_outcome', sa.String(length=20), nullable=False, comment='Hasil pemrosesan terakhir: success | duplicate | failed | skipped_unchanged'),
    sa.Column('last_seen_job_id', sa.Integer(), nullable=True, comment='ID job terakhir yang memindai/melihat berkas ini'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu pertama kali berkas terdeteksi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu pembaruan status berkas terakhir'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_job_id'], ['job_ingest.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['scraping_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'relative_path', name='uq_source_files_source_path')
    )
    op.create_index(op.f('ix_source_files_id'), 'source_files', ['id'], unique=False)
    op.create_index(op.f('ix_source_files_source_id'), 'source_files', ['source_id'], unique=False)
    op.add_column('documents', sa.Column('extraction_engine', sa.String(length=100), nullable=True, comment='Nama engine/model ekstraksi spesifik (misal: surya_ocr, pdfplumber, llm_v1)'))
    op.add_column('job_ingest', sa.Column('total_found', sa.Integer(), nullable=True, comment='Total berkas yang ditemukan pada sumber'))
    op.add_column('job_ingest', sa.Column('processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Jumlah berkas yang telah diproses'))
    op.add_column('job_ingest', sa.Column('skipped_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Jumlah berkas yang dilewati tanpa perubahan (skipped_unchanged)'))
    op.add_column('scraping_sources', sa.Column('source_type', sa.Enum('situs_web', 'folder_lokal', 'onedrive_public', name='jenissumber', native_enum=False), server_default='situs_web', nullable=False, comment='Jenis sumber: situs_web | folder_lokal | onedrive_public'))
    op.add_column('scraping_sources', sa.Column('crawl_depth', sa.Integer(), nullable=True, comment='Kedalaman crawling (1-5) khusus untuk situs_web; NULL untuk folder'))
    op.add_column('scraping_sources', sa.Column('recursive', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Pindai subfolder secara rekursif (khusus folder_lokal)'))
    op.add_column('scraping_sources', sa.Column('default_access_classification', sa.Enum('publik', 'non_publik', name='klasifikasiakses', native_enum=False), server_default='publik', nullable=False, comment='Klasifikasi akses default untuk dokumen dari sumber ini'))
    op.add_column('scraping_sources', sa.Column('default_document_role', sa.Enum('corpus_eksisting', 'draft_kajian', name='perandokumen', native_enum=False), server_default='corpus_eksisting', nullable=False, comment='Peran dokumen default untuk dokumen dari sumber ini'))
    op.add_column('scraping_sources', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu terakhir sumber dijalankan'))
    op.add_column('scraping_sources', sa.Column('last_run_status', sa.String(length=20), nullable=True, comment='Status terakhir: selesai | gagal | berjalan'))
    op.add_column('scraping_sources', sa.Column('last_run_message', sa.Text(), nullable=True, comment='Ringkasan atau pesan hasil eksekusi terakhir'))
    op.add_column('scraping_sources', sa.Column('last_job_id', sa.Integer(), nullable=True, comment='ID job ingest terakhir yang mengeksekusi sumber ini'))
    op.alter_column('scraping_sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nama/label situs/folder sumber, misal: JDIH OJK, Folder POJK 2023',
               existing_comment='Nama/label situs sumber scraping, misal: JDIH OJK',
               existing_nullable=False)
    op.alter_column('scraping_sources', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment='Alamat URL atau jalur folder lokal sumber (wajib unik)',
               existing_comment='URL situs sumber scraping (wajib unik)',
               existing_nullable=False)
    op.create_index(op.f('ix_scraping_sources_source_type'), 'scraping_sources', ['source_type'], unique=False)
    op.create_foreign_key('fk_scraping_sources_last_job_id_job_ingest', 'scraping_sources', 'job_ingest', ['last_job_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_scraping_sources_last_job_id_job_ingest', 'scraping_sources', type_='foreignkey')
    op.drop_index(op.f('ix_scraping_sources_source_type'), table_name='scraping_sources')
    op.alter_column('scraping_sources', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment='URL situs sumber scraping (wajib unik)',
               existing_comment='Alamat URL atau jalur folder lokal sumber (wajib unik)',
               existing_nullable=False)
    op.alter_column('scraping_sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nama/label situs sumber scraping, misal: JDIH OJK',
               existing_comment='Nama/label situs/folder sumber, misal: JDIH OJK, Folder POJK 2023',
               existing_nullable=False)
    op.drop_column('scraping_sources', 'last_job_id')
    op.drop_column('scraping_sources', 'last_run_message')
    op.drop_column('scraping_sources', 'last_run_status')
    op.drop_column('scraping_sources', 'last_run_at')
    op.drop_column('scraping_sources', 'default_document_role')
    op.drop_column('scraping_sources', 'default_access_classification')
    op.drop_column('scraping_sources', 'recursive')
    op.drop_column('scraping_sources', 'crawl_depth')
    op.drop_column('scraping_sources', 'source_type')
    op.drop_column('job_ingest', 'skipped_count')
    op.drop_column('job_ingest', 'processed_count')
    op.drop_column('job_ingest', 'total_found')
    op.drop_column('documents', 'extraction_engine')
    op.drop_index(op.f('ix_source_files_source_id'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_id'), table_name='source_files')
    op.drop_table('source_files')
    # ### end Alembic commands ###
