"""step7_site_scan

Revision ID: bc5089a2ab26
Revises: 39905e7be840
Create Date: 2026-09-26 22:48:12.627457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc5089a2ab26'
down_revision: Union[str, None] = '39905e7be840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='ID sumber scraping yang dipindai (NULL jika sumber dihapus)'),
    sa.Column('start_url', sa.Text(), nullable=False, comment='Salinan URL awal saat sesi pemindaian dimulai'),
    sa.Column('crawl_depth', sa.Integer(), nullable=False, comment='Kedalaman penelusuran (1-5)'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='Mode crawler: simple_http | external_module | push'),
    sa.Column('crawler_name', sa.String(length=100), nullable=True, comment='Nama identitas crawler yang mengeksekusi'),
    sa.Column('status', sa.Enum('antrian', 'memindai', 'siap_dipilih', 'menarik', 'selesai', 'gagal', 'dibatalkan', name='statuspindai', native_enum=False), server_default='antrian', nullable=False, comment='Status sesi: antrian | memindai | siap_dipilih | menarik | selesai | gagal | dibatalkan'),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Flag permintaan pembatalan oleh pengguna'),
    sa.Column('pages_visited', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Jumlah halaman HTML yang telah dikunjungi'),
    sa.Column('candidates_total', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total kandidat PDF yang ditemukan'),
    sa.Column('candidates_new', sa.Integer(), server_default=sa.text('0'), nullable=False, comment="Jumlah kandidat berstatus 'baru'"),
    sa.Column('candidates_existing', sa.Integer(), server_default=sa.text('0'), nullable=False, comment="Jumlah kandidat berstatus 'sudah_ada'"),
    sa.Column('candidates_uncertain', sa.Integer(), server_default=sa.text('0'), nullable=False, comment="Jumlah kandidat berstatus 'mungkin_ada'"),
    sa.Column('truncated', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True jika pemindaian terpotong karena mencapai batas halaman/kandidat'),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Daftar pesan error/peringatan selama pemindaian'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Pesan kesalahan fatal jika status gagal'),
    sa.Column('destination', sa.Enum('knowledge_base', 'unduh_folder', name='tujuantarik', native_enum=False), nullable=True, comment='Tujuan penarikan: knowledge_base | unduh_folder'),
    sa.Column('pull_job_id', sa.Integer(), nullable=True, comment='ID job ingest saat proses penarikan berjalan'),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True, comment='ID user yang meminta pemindaian'),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu sesi diklaim oleh worker (untuk mode push)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu pemindaian mulai berjalan'),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu pemindaian selesai dan siap dipilih'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu penarikan atau sesi selesai'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Waktu pencatatan sesi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu pembaruan sesi terakhir'),
    sa.ForeignKeyConstraint(['pull_job_id'], ['job_ingest.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['scraping_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_sessions_id'), 'scan_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scan_sessions_source_id'), 'scan_sessions', ['source_id'], unique=False)
    op.create_index(op.f('ix_scan_sessions_status'), 'scan_sessions', ['status'], unique=False)
    op.create_table('scan_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False, comment='ID sesi pemindaian pemilik kandidat ini'),
    sa.Column('url', sa.Text(), nullable=False, comment='URL kandidat PDF yang sudah dinormalisasi'),
    sa.Column('url_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash dari normalized URL untuk pengecekan cepat & constraint unik'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Nama berkas dari path URL atau Content-Disposition'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='Ukuran berkas dalam bytes dari Content-Length (jika tersedia)'),
    sa.Column('found_on_page', sa.Text(), nullable=True, comment='URL halaman tempat tautan PDF ini ditemukan'),
    sa.Column('depth', sa.Integer(), nullable=False, comment='Kedalaman halaman tempat tautan ditemukan'),
    sa.Column('match_status', sa.Enum('baru', 'sudah_ada', 'mungkin_ada', name='statuskandidat', native_enum=False), nullable=False, comment='Status kecocokan KB: baru | sudah_ada | mungkin_ada'),
    sa.Column('match_reason', sa.String(length=30), nullable=True, comment='Alasan pencocokan: url_sama | nama_dan_ukuran_sama'),
    sa.Column('match_document_id', sa.Integer(), nullable=True, comment='ID dokumen di KB yang cocok jika match_status sudah_ada atau mungkin_ada'),
    sa.Column('selected', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Status centang pengguna untuk ditarik'),
    sa.Column('pull_outcome', sa.String(length=20), nullable=True, comment='Hasil penarikan: success | duplicate | failed | downloaded'),
    sa.Column('document_id', sa.Integer(), nullable=True, comment='ID dokumen regulasi baru jika ditarik ke knowledge_base'),
    sa.Column('failure_id', sa.Integer(), nullable=True, comment='ID baris ingest_failures jika penarikan gagal'),
    sa.Column('export_path', sa.Text(), nullable=True, comment='Jalur penyimpanan relatif untuk tujuan unduh_folder'),
    sa.Column('message', sa.Text(), nullable=True, comment='Pesan/detail hasil penarikan atau error'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['failure_id'], ['ingest_failures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'url_hash', name='uq_scan_candidates_scan_url_hash')
    )
    op.create_index(op.f('ix_scan_candidates_id'), 'scan_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_scan_candidates_match_status'), 'scan_candidates', ['match_status'], unique=False)
    op.create_index(op.f('ix_scan_candidates_scan_id'), 'scan_candidates', ['scan_id'], unique=False)
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=True, comment='Nama file asli dokumen saat diunggah/diingest'))
    op.create_index('ix_documents_source_url_hash', 'documents', ['source_url'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_source_url_hash', table_name='documents', postgresql_using='hash')
    op.drop_column('documents', 'original_filename')
    op.drop_index(op.f('ix_scan_candidates_scan_id'), table_name='scan_candidates')
    op.drop_index(op.f('ix_scan_candidates_match_status'), table_name='scan_candidates')
    op.drop_index(op.f('ix_scan_candidates_id'), table_name='scan_candidates')
    op.drop_table('scan_candidates')
    op.drop_index(op.f('ix_scan_sessions_status'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_source_id'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_id'), table_name='scan_sessions')
    op.drop_table('scan_sessions')
    # ### end Alembic commands ###
