"""inisialisasi alembic dan tabel baru

Revision ID: f841df680a0f
Revises: 
Create Date: 2026-09-14 21:18:45.974376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f841df680a0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Username unik untuk login'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Password yang sudah di-hash dengan bcrypt'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Peran akses: admin | user'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Status akun — False berarti akun dinonaktifkan'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User yang melakukan aksi; NULL jika aksi sistem / anonim'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Kode aksi: LOGIN | DOWNLOAD_PDF | DELETE_DOC | dsb.'),
    sa.Column('target_resource', sa.String(length=255), nullable=True, comment="Nama atau ID resource yang dikenai aksi, misal: 'document:42'"),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Alamat IP klien saat melakukan aksi'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Waktu kejadian (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
